### ISSUE TITLE
"New Folder" input error message persists after modal close

### ISSUE THREAD

**Issue by rosasam** [Teknologforeningen/fotogalleri#51]
Steps to reproduce:

1. Open "New Folder" modal (as admin).
2. Input a name that creates an error message (e.g. a name with / in it).
3. Observe error message.
4. Close modal, reopen modal.
5. Observe the error message again.

**Comment by c00k133** [comment]
Fixed by: https://github.com/Teknologforeningen/fotogalleri/pull/72
