### ISSUE TITLE
ImagePath model: uniqueness constraint for full paths

### ISSUE THREAD

**Issue by rosasam** [Teknologforeningen/fotogalleri#54]
ImagePath models should have a uniqueness constraint for full paths, e.g. two paths "/full/path/name" and "/full/path/name" should not be allowed, even though two paths can be called "name", as long as their full path is different.

**Comment by c00k133** [comment]
This was handled and close in the following PR: https://github.com/Teknologforeningen/fotogalleri/pull/56
